### ISSUE TITLE
misc/question: use permissions.query instead of mediaDevices.getUserMedia()

### ISSUE THREAD

**Issue by carloscarvallo** [open-voip-alliance/WebphoneLib#43]
Sorry for put this on issues.

Have you thought about using `navigator.permissions.query()` instead of `mediaDevices.getUserMedia()` for browsers that supports this API?

Maybe this can eliminate the need to open a stream in the `requestPermission()` method in `Media class`, if the browser does not support maybe can fallback to `.getUserMedia()`, the gotcha is that the `permissions.query()` does not prompt user permissions, if this had been denied, in that case can fallback also to `.getUserMedia()` to open the prompt.

**Comment by carloscarvallo** [comment]
Great lib by the way, greetings!

**Comment by confususs** [comment]
First of all, sorry for the late response! I completely forgot about it.. Thank you for your suggestion, we'll look into this and get back to you soon!

Thanks for the compliment :smile:.

**Comment by Dagg-h** [comment]
Thanks for your suggestion! Made a implementation of it :)
