### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by salvatorelapi** [open-voip-alliance/WebphoneLib#46]
![Log](https://user-images.githubusercontent.com/5333340/81394544-5f2e3200-9122-11ea-942d-8b0418412b5b.PNG)
### Version

{version or tag here}

### File / Feature

{file or feature containing the issue}

### Expected behaviour

{what should happen}

### Actual behaviour

{what happens}

### Stacktrace / Error message

    {paste here}

### Other info

{anything else that might be related/useful}

**Comment by confususs** [comment]
Oops, that is not supposed to happen.. We will look into this and get back to you soon. Thanks for reporting!

**Comment by Dagg-h** [comment]
Fixed, just merged now!
