### ISSUE TITLE
Feature: Local and Remote media streams

### ISSUE THREAD

**Issue by moxival** [open-voip-alliance/WebphoneLib#47]
### Version

0.2.10

### File / Feature

Would it be possible to expose the local and remote media streams trough the Session (or the client)? The library is really easy and simple to work with but I could not find a way to access the media streams.

**Comment by confususs** [comment]
It might be possible, we will look into it soon! Thank you for creating this issue :smile:

**Comment by moxival** [comment]
Thanx for the reply, fingers crossed 🤞

**Comment by patrickswijgman** [comment]
We've added a pull request #48 that adds getters to the session class which you can use to access the local and remote streams :) Please let us know if this solves your issue.

**Comment by moxival** [comment]
Hi, thanks so much, yes that will be perfect for our use case

**Comment by moxival** [comment]
Hey @patrickswijgman when can we expect this feature to make it to a new release?

**Comment by patrickswijgman** [comment]
@moxival Yup, If everything goes according to plan I will make a release today :slightly_smiling_face:
