### ISSUE TITLE
Cannot Copy to clipboard: write EPIPE

### ISSUE THREAD

**Issue by Meti27** [open-voip-alliance/WebphoneLib#55]
version : `0.2.12`

Os : `centos 7`

when i'm trying to run `npm run demo`  and its successfully serve it but before serve its showing  this error : 
```
Error : Cannot copy to clipboard: write EPIPE
```
![image](https://user-images.githubusercontent.com/11253027/88622842-e1dae380-d0b8-11ea-8f7b-7de1e2c259ec.png)

but at the first it give me an error about `xclip/exsel` not installed , and i install it and then give me the `write EPIPE` error.

anyway with this error its still serve the demo and when i run myip:1235 like `192.168.1.60:1235/demo` its just showing a blank page and when i open the instpect its showing this errors : 
![image](https://user-images.githubusercontent.com/11253027/88622737-adffbe00-d0b8-11ea-920c-20904af90593.png)

thanks in advance.

**Comment by confususs** [comment]
Thanks for filing a report! The EPIPE issue is probably caused by serve trying to copy the url to your clipboard, while somehow it has no access to it. I have the same error =/. 

Does the url work if you add a trailing slash to it? (like `192.168.1.60:1235/demo/` or `localhost:1235/demo/`)

**Comment by PM5544** [comment]
Hi @Meti27,
Could you try to add a slash at the end of your URL? Like so `192.168.1.60:1235/demo/`.
This had me puzzled also and there's a pull request in the making for this (adding `"trailingSlash": true` in the `/serve.json`).
Hope it helps!

**Comment by Meti27** [comment]
@confususs  @PM5544  Thanks , and sorry for late response.
i tried this url `192.168.1.60:1235/demo/` and the errors in console about `min.css`,`index.mjs` disappeared!
but new error appeared :
![image](https://user-images.githubusercontent.com/11253027/88691465-234bad00-d112-11ea-99fc-8816903d0db8.png)
and the page is still blank.

**Comment by PM5544** [comment]
@Meti27 Ah right that's another thing I also encountered when trying to get it working for the first time (also there's a PR for that). The readme states `$ touch demo/config.js` but it's actually looking for an mjs file so if you rename the `demo/config.js` file to `demo/config.mjs` (notice the extra 'm' in the extension) then it should work.

**Comment by Meti27** [comment]
@PM5544  thanks alot . i change `demo/config.js` to `demo/config.mjs` and its ok. but now i face new errors 
![image](https://user-images.githubusercontent.com/11253027/88758006-ae618d00-d17c-11ea-87df-4b5602b8fd3c.png)

could be this error because of my `config.mjs` settiings? this is my `config.mjs` content:
```
export const authorizationUserId = 3007;
export const password            = 'pass3007';
export const yourPlatformURL     = '192.168.1.60'
export const accountUri          = 'sip:3007@192.168.1.60';
export const subscribeTo         = 'sip:3007@192.168.1.60';
```


and the authId , password , url , i think should be ok.

**Comment by PM5544** [comment]
As far as I know the `authorizationUserId` also needs to be a string, besides that it looks like your browser is unsupported. I wonder what browser version you're running because Chrome (based on the icon in your devtools) has support for everything for ages. What browser and browser version and OS and OS version combination are you using?

**Comment by Meti27** [comment]
the operating system that using to test it is : 
os : windows 10
browser : chrome Version 84.0.4147.105 (Official Build) (64-bit) --- this is last version.
and i change the `authorizationUserId` to string `'3007'` and its still the same.
its interesting that i test it on Mozilla browser and its say its not supported too.
![image](https://user-images.githubusercontent.com/11253027/88771182-1bcce800-d194-11ea-8c95-3ca775ae8f99.png)

**Comment by PM5544** [comment]
That should work I think.
I'm afraid this is something that's over my head. Hoping @confususs knows more about what could cause this....

**Comment by confususs** [comment]
It might be that you should use http://localhost:1235/demo/ instead. I'm guessing the browser treats 192.168.1.60 as an external address and wants it to have some additional protections 'normal' websites also have. So it will not give you access to the mediaDevices before it is sure that the website is secure. 

For localhost it knows that you're fine security-wise =]

**Comment by Meti27** [comment]
@PM5544  Thanks again.
@confususs thank you , but do you have any suggestion how can i do that? its issablel on centos 7 , how can i run `lcoahost:1235/demo/`  on itself?

**Comment by confususs** [comment]
There is nothing you have to do configuration-wise, so it should be accessible within the browser just like you access 192.168.1.60:1235/demo/, but instead of that link you access http://localhost:1235/demo/. Or do you want to access the website on a different pc?

**Comment by Meti27** [comment]
yes , im trying to access it from another pc. 
what about ssl? should i install ssl and try it on https?

**Comment by confususs** [comment]
If you want it to work in chrome without HTTPS and you're just testing / developing, you can goto this link:

chrome://flags/#unsafely-treat-insecure-origin-as-secure

And add `http://192.168.1.60:1235`. Then it should work!

**Comment by Meti27** [comment]
@confususs   thanks , i try it its not finding `index.mjs`
![image](https://user-images.githubusercontent.com/11253027/88889287-1daab000-d255-11ea-8952-e7ab7e320f1f.png)

**Comment by Meti27** [comment]
i refresh the page and its again `not supported browser error`
![image](https://user-images.githubusercontent.com/11253027/88890039-441d1b00-d256-11ea-85db-7e2d20840e78.png)

and if i try it with ssl:
![image](https://user-images.githubusercontent.com/11253027/88890088-57c88180-d256-11ea-84e7-bdd568e0e84b.png)

but on main domain its not have a valid ssl too but its going on and load the page
![image](https://user-images.githubusercontent.com/11253027/88890163-76c71380-d256-11ea-842f-2d22e6d70148.png)

**Comment by confususs** [comment]
That is interesting, can you show me what happens in the network tab? Also, could you check if  the "dist" folder on the server contains the 'index.mjs'? And are you sure the [setting](https://github.com/open-voip-alliance/WebphoneLib/issues/55#issuecomment-665536051) is still active?

When the code is served using `npm run demo` it will unfortunately not have SSL support out-of-the-box. If you want to introduce support for that you would have to use something like nginx or use a static site host like Netlify. :slightly_smiling_face:

**Comment by Meti27** [comment]
i didn't set the server ip in here , i set my ip , and now its ok
![image](https://user-images.githubusercontent.com/11253027/88893607-d542c080-d25b-11ea-8e27-5aa6cfe52de5.png)

and now its ok

![image](https://user-images.githubusercontent.com/11253027/88893697-f9060680-d25b-11ea-9817-1801a6f9ca4d.png)


but its not registering 
when click on register button , the error shows in debug console
```
calling CONFIGURATION_ERROR: Invalid value "wss://websocket.192.168.1.60" for parameter 'wsServers'
CONFIGURATION_ERROR: Invalid value "wss://websocket.192.168.1.60" for parameter 'wsServers'
at ConfigurationError.Exception [as constructor] (http://192.168.1.60:1235/dist/index.mjs:5370:28)
at ConfigurationError.LegacyException [as constructor] (http://192.168.1.60:1235/dist/index.mjs:12420:28)
at new ConfigurationError (http://192.168.1.60:1235/dist/index.mjs:12432:32)
at WrappedTransport.Transport.loadConfig (http://192.168.1.60:1235/dist/index.mjs:15360:27)
at new Transport (http://192.168.1.60:1235/dist/index.mjs:14805:37)
at new WrappedTransport (http://192.168.1.60:1235/dist/index.mjs:27079:1)
at new UserAgent (http://192.168.1.60:1235/dist/index.mjs:17386:26)
at ReconnectableTransport.uaFactory (http://192.168.1.60:1235/dist/index.mjs:27831:16)
at ReconnectableTransport.configureUA (http://192.168.1.60:1235/dist/index.mjs:27319:31)
at ReconnectableTransport.connect (http://192.168.1.60:1235/dist/index.mjs:27177:18)
```

and this is my config.mjs
```
export const authorizationUserId = '3007';
export const password            = 'pass3007';
export const yourPlatformURL     = '192.168.1.60'
export const accountUri          = 'sip:3007@192.168.1.60';
export const subscribeTo         = 'sip:3007@192.168.1.60';
```

**Comment by confususs** [comment]
I see.. That is my bad, sorry! 

The culprit is [this line](https://github.com/open-voip-alliance/WebphoneLib/blob/master/demo/lib/calling.mjs#L29), you could change that to something like:

```  wsServers: `wss://${CONF.yourPlatformURL}`,```

**Comment by Meti27** [comment]
for now i change it to `wsServers: 'wss://192.168.1.60:8089/ws',` and its ok.
thank you.
