### ISSUE TITLE
First installation attempt

### ISSUE THREAD

**Issue by hamedkouhfallah** [open-voip-alliance/WebphoneLib#57]
### Actual behaviour

Hi,
I am trying to install on Centos 7, after running "npm i && npm run demo" and some while I have got this error:
It seems that after running "npm run demo" this error is shownig.
thanks

### Stacktrace / Error message

> webphone-lib@0.2.12 demo /root/WebphoneLib
> run-p build-watch serve

> webphone-lib@0.2.12 build-watch /root/WebphoneLib
> npm run clean && rollup -cw

> webphone-lib@0.2.12 serve /root/WebphoneLib
> serve -l 1235

/root/WebphoneLib/node_modules/serve/bin/serve.js:35
const updateCheck = async (isDebugging) => {
                          ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

npm ERR! Linux 3.10.0-1062.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "run" "serve"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! webphone-lib@0.2.12 serve: `serve -l 1235`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webphone-lib@0.2.12 serve script 'serve -l 1235'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webphone-lib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     serve -l 1235
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webphone-lib
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webphone-lib
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/WebphoneLib/npm-debug.log
ERROR: "serve" exited with 1.

npm ERR! Linux 3.10.0-1062.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "demo"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! webphone-lib@0.2.12 demo: `run-p build-watch serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webphone-lib@0.2.12 demo script 'run-p build-watch serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webphone-lib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     run-p build-watch serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webphone-lib
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webphone-lib
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/WebphoneLib/npm-debug.log

### Other info

{anything else that might be related/useful}

**Comment by PM5544** [comment]
Wow, that is a very old version of Node I'd suggest updating to a recent version if your other projects allow that. If you have other projects that require this version of Node I'd suggest using NVM to allow you to easily switch between versions when needed.

**Comment by hamedkouhfallah** [comment]
Thank you, ,you are right, Now I have instaaled latest Node js v12
after installing and RUN, I see image No1.
also after accessing WebUL by http://192.168.2.101:1235/ I can see image No2
and after clicking DEMO folder I see Image No3

also this is my DEMO config.js configuration:
```
export const authorizationUserId = 3001;
export const password = 'pass3001';
export const yourPlatformURL = '192.168.2.101'
export const accountUri = `sip:3001@192.168.2.101`;
export const subscribeTo = `sip:3001@192.168.2.101`;

```


thanks
![1](https://user-images.githubusercontent.com/54766086/88887974-ac69fd80-d252-11ea-9615-6ac5796cb135.png)

![2](https://user-images.githubusercontent.com/54766086/88887985-af64ee00-d252-11ea-82ec-3861d9af8ca9.png)


![3](https://user-images.githubusercontent.com/54766086/88887992-b2f87500-d252-11ea-933a-068b2666cfdb.png)

**Comment by PM5544** [comment]
Great!
To fix this you should rename the `demo/config.js` file and the page should load. There's a typo in the readme.md stating that you should `$ touch demo/config.js` but it should be a `demo/config.mjs`. There's a PR to fix the readme for this so this should be fixed soon.

**Comment by hamedkouhfallah** [comment]
Yes, I found it,
I have change config.js to config.mjs.
Now the UI web page is white blank like image 3 in previous post.
also this is my Console errors:


[192.168.2.101-1596090957519.log](https://github.com/open-voip-alliance/WebphoneLib/files/4999265/192.168.2.101-1596090957519.log)



![image](https://user-images.githubusercontent.com/54766086/88889039-aecd5700-d254-11ea-93ce-5746cda9cb87.png)

**Comment by PM5544** [comment]
Could you please check if the instructions found [here](https://github.com/open-voip-alliance/WebphoneLib/issues/55#issuecomment-665507010) solves these issues?

**Comment by hamedkouhfallah** [comment]
thank you,
I set the chrome setting in 2 form:
1. 
![11](https://user-images.githubusercontent.com/54766086/88890425-db826e00-d256-11ea-8a41-41231e13f0f5.png)


2.
![12](https://user-images.githubusercontent.com/54766086/88890431-dcb39b00-d256-11ea-91b0-de54e51981e4.png)



in both the same error on console and I have blank white page.

![13](https://user-images.githubusercontent.com/54766086/88890440-e0dfb880-d256-11ea-9c55-b2f2c3a19410.png)



** also I have tried on FIREFOX, I have same page but here is the firefox console errors, may be they help.

[console-export-2020-7-30_11-19-8.txt](https://github.com/open-voip-alliance/WebphoneLib/files/4999347/console-export-2020-7-30_11-19-8.txt)

![14](https://user-images.githubusercontent.com/54766086/88890509-f94fd300-d256-11ea-9a89-9134e7ffc13a.png)



thank you in advanced

**Comment by PM5544** [comment]
Could you try using localhost to serve the webphoneLib? I assume it will work when you try running the webphoneLib on the same machine as you use to look at it in a browser. So clone the repo and run node on that machine. I assume there are still some restrictions in play because of the non secure domain. Opening localhost has some different restrictions so that might work. Can you try that?

**Comment by confususs** [comment]
Could it be that there is a mismatch between the config and the server you're trying to reach? 

I see that you're reaching the server on http://192.168.2.101:1235 but in the configuration there is http://192.168.1.101:1235, just fyi :slightly_smiling_face:

**Comment by hamedkouhfallah** [comment]
Thank you
It was my fault, It is now showing the first page.
I am going to register and testing 

thank you

**Comment by confususs** [comment]
No problem! Good luck with your project :smile:
