### ISSUE TITLE
Help to install and use 

### ISSUE THREAD

**Issue by danicarla** [open-voip-alliance/WebphoneLib#61]
Hi guys .. I downloaded the ZIP file but I didn't understand how it works...

When I try to open the demo, a blank page as load, and this message as displayed on console: "Failed to load the module script: The server responded with a non-JavaScript MIME type of" ". The strict MIME type check is applied to the scripts module by HTML specification. "

The instructions ask me to add a code to the "demo / config.mjs" file but that file does not exist. Do I need to create?

**Comment by PM5544** [comment]
Hello @danicarla
When you have unzipped the downloaded repo you should be able to continue from [the getting started instructions](https://github.com/open-voip-alliance/WebphoneLib#getting-started). 
The file `./demo/config.mjs` should be created by you indeed.
Good luck and if there's anything else that is unclear, just reply here!
