### ISSUE TITLE
Demo config & Demo/lib/calling.mjs

### ISSUE THREAD

**Issue by WorkingClass** [open-voip-alliance/WebphoneLib#66]
Hello,

Trying to connect the demo to my dev platform, kazoo, and found out that the config is not working.

1. I would suggest to use "realm" or "domain" instead of "yourPlatformURL". The more usual way.
2. Demo/lib/calling.mjs has an hardcoded subdomain "websocket.";
...
const transport = {
  wsServers: `wss://websocket.${CONF.yourPlatformURL}`,
  iceServers: []
};
...

Still testing...

Thanks,
Vic

**Comment by Dagg-h** [comment]
Hey!

Cool that you are trying out the WebphoneLib :smile: 
We will remove the hard coded part and I will use your suggestion! Check out this pull request: https://github.com/open-voip-alliance/WebphoneLib/pull/65 

Thanks for the suggestions!
