### ISSUE TITLE
How to make  a conference?

### ISSUE THREAD

**Issue by devrogergroff** [open-voip-alliance/WebphoneLib#85]

**Comment by confususs** [comment]
Unfortunately it is not possible to create a conference call using the webphone-lib. You could however, use the webphone-lib to call into a conference server which does allow multiple participants. 

Another way that you _could_ go about it, is to add your own logic to the webphone-lib to be able to call multiple participants and let them think that they are in a conference call with one another. Note that each participant would then have to call every participant, which is quite bandwidth-intensive. Currently this feature is not (and probably will not be) in the scope of the project.
