### ISSUE TITLE
Support for outgoing call onProgress message emit in session 

### ISSUE THREAD

**Issue by rupraj-mitel** [open-voip-alliance/WebphoneLib#90]
Version
0.2.18
### Expected behaviour
In session.ts can we have the following 
onProgress: (message) => {
          log.debug('Session is in progress', this.constructor.name);
          this.emit('sessionProgress', message);
          onProgress();
        }

**Comment by confususs** [comment]
Cool that you're using the lib! Just curious, would it also work if you could get the initial progress message like this? 

```
session.progressed().then(({ message }) => { ..your code });
```

Or do you need something like what you suggested instead? :) 

Either way feel free to submit a PR, or I'll get around to do it when I have time soon.

**Comment by rupraj-mitel** [comment]
session.progressed().then(({ message }) => { ..your code });
This will also do the job, I hope.
If you can do the code change at your end. :)
Thanks in advance.

**Comment by confususs** [comment]
Added this feature in 0.2.19 :tada: :smile:
